version: "3.8"

services:
  app:
    build: .
    container_name: soat-techchallenge-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=soat
      - DB_USER=postgres
      - DB_PASSWORD=postgres

  db:
    image: postgres:13-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=soat

volumes:
  postgres-data:
