spring:
  application:
    name: "soat-techchallenge"
  sql:
    init:
      continue-on-error: true
  datasource:
    url: jdbc:postgresql://localhost:5432/soat
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 200000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mercado-pago:
    access-token: ${MERCADO_PAGO_ACCESS_TOKEN}
    user-id: ${MERCADO_PAGO_USER_ID}
    pos: ${MERCADO_PAGO_POS}
    callback-url: ${MERCADO_PAGO_CALLBACK_URL}
    webhook-token: ${MERCADO_PAGO_WEBHOOK_TOKEN}

#  metrics:
#    export:
#      prometheus:
#        enabled: true

    actuator:
      endpoints:
        web:
          exposure:
            include: '*'
      endpoint:
        prometheus:
          enabled: true
      metrics:
        enable:
          all: true

server:
  port: 8080
  servlet:
    context-path: /soat-fast-food

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /soat-fast-food/actuator
      exposure:
        include:
          - health
          - info

logging:
  level:
    root: WARN
    org.springframework: WARN
    org.hibernate: WARN
    com.zaxxer.hikari: INFO
    com.store.soattechchallenge: INFO