apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: tech-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-challenge-db
  template:
    metadata:
      labels:
        app: tech-challenge-db
    spec:
      containers:
        - name: tech-challenge-db
          image: public.ecr.aws/p6c0d2v5/fiap-soat-techchallenge-db:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"

          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
