apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: tech-challenge
spec:
  type: NodePort
  selector:
    app: tech-challenge-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
